package sdmx.converter;

/* CVS $Id: $ */

import com.hp.hpl.jena.rdf.model.*;

/**
 * Vocabulary definitions from sdmx.rdf
 * @author Auto-generated by schemagen on 10 Mar 2015 14:54
 */
public class Sdmx {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/linked-data/sdmx#";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );

    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "0.3";

    /** <p>Indicates an additional component used as the primary measure within the SDMX
     *  data. In the case of multi-measure data sets the RDF representation uses the
     *  specific measure rather than a subsuming overall measure. This property records
     *  the subsuming primary measure (typically sdmx-measure:obsValue) to enable
     *  round tripping of this information.</p>
     */
    public static final Property primaryMeasure = m_model.createProperty( "http://purl.org/linked-data/sdmx#primaryMeasure" );

    public static final Resource CodeList = m_model.createResource( "http://purl.org/linked-data/sdmx#CodeList" );

    /** <p>Denotes an SDMX concept, used in the particular SDMX terminological sense,
     *  which is in principle narrower than skos:Concept</p>
     */
    public static final Resource Concept = m_model.createResource( "http://purl.org/linked-data/sdmx#Concept" );

    /** <p>Abstract superclass of classes denoting statistical roles which be played
     *  by concepts</p>
     */
    public static final Resource ConceptRole = m_model.createResource( "http://purl.org/linked-data/sdmx#ConceptRole" );

    /** <p>concept for a dimension or attribute that plays the role of an identifier
     *  where the identifier is taken from a known system of counts (e.g. the Nth
     *  current dataset update for a given day)</p>
     */
    public static final Resource CountRole = m_model.createResource( "http://purl.org/linked-data/sdmx#CountRole" );

    /** <p>A specialization of qb:DataStructureDefinition which additional constraints:
     *  if there are multiple measures then a MeasureDimensionProperty must be included
     *  in the DSD</p>
     */
    public static final Resource DataStructureDefinition = m_model.createResource( "http://purl.org/linked-data/sdmx#DataStructureDefinition" );

    /** <p>concept for a dimension or attribute that plays the role of the DataAttribute
     *  subject to whom the data refers (e.g. the reporting agent for primary reporting,
     *  the country for secondary reporting)</p>
     */
    public static final Resource EntityRole = m_model.createResource( "http://purl.org/linked-data/sdmx#EntityRole" );

    /** <p>concept for a dimension or attribute that plays the role of frequency</p> */
    public static final Resource FrequencyRole = m_model.createResource( "http://purl.org/linked-data/sdmx#FrequencyRole" );

    /** <p>concept for a dimension or attribute that plays the role of an identifier
     *  which is taken from a known scheme of identifiers.</p>
     */
    public static final Resource IdentityRole = m_model.createResource( "http://purl.org/linked-data/sdmx#IdentityRole" );

    /** <p>concept for a dimension that plays the role of identifying a type of measure</p> */
    public static final Resource MeasureTypeRole = m_model.createResource( "http://purl.org/linked-data/sdmx#MeasureTypeRole" );

    /** <p>concept for a dimension or attribute that plays the role of a date/time identifier
     *  in the KeyFamily which is not related to the time of the observation</p>
     */
    public static final Resource NonObsTimeRole = m_model.createResource( "http://purl.org/linked-data/sdmx#NonObsTimeRole" );

    /** <p>concept for a measure that plays the role of the observation in a time series</p> */
    public static final Resource PrimaryMeasureRole = m_model.createResource( "http://purl.org/linked-data/sdmx#PrimaryMeasureRole" );

    /** <p>concept for a dimension that specifies the time of the observation of the
     *  primaryMeasure</p>
     */
    public static final Resource TimeRole = m_model.createResource( "http://purl.org/linked-data/sdmx#TimeRole" );

    /** <p>The concept corresponding to the generic measure type dimension which indicates
     *  which measure is being denoted by the primary measure on an observation</p>
     */
    public static final Resource measureTypeConcept = m_model.createResource( "http://purl.org/linked-data/sdmx#measureTypeConcept" );

}
